config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#homepage'

  get 'my_tools', to: 'tools#mine'

  resources :tools do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [:show]
  # resources :reviews, only: [ :destroy ]


  get 'dashboard', to: 'pages#dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tool
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tool
  belongs_to :user
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :users, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
  has_many :reviews, dependent: :destroy
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, uniqueness: true
  # validates :user_address, presence: true
  has_many :bookings
  has_many :tools, through: :bookings
  has_many :my_tools, class_name: 'Tool'


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # This is the bookingscontroller, superfluous commenting
  def index
    @bookings = policy_scope(Booking)
    # @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    @user = current_user
  end

  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    # Linking the models
    @tool = Tool.find(params[:tool_id])
    @booking.tool = Tool.find(params[:tool_id])
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy(booking_params)
    redirect_to bookings_path
  end

private

  def booking_params
    params.require(:booking).permit(:start_date,:end_date)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: :homepage

  def homepage

  end

  def dashboard
    @bookings = current_user.bookings
    @my_tools = current_user.my_tools
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @tool in our `simple_form_for`
    @tool = Tool.find(params[:tool_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @tool = Tool.find(params[:tool_id])
    # we need `tool_id` to asssociate review with corresponding tool
    @review.tool = @tool
    @review.user = current_user
    authorize @review
     if @review.save
      respond_to do |format|
        format.html { redirect_to tool_path(@review.tool) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'tools/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: :homepage

  def index

    @render_footer = true
    @tools = policy_scope(Tool)
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @tools = Tool.where(sql_query, query: "%#{params[:query]}%")
    else
      @tools = Tool.all
    end
    authorize @tools
    @locations = Tool.where.not(latitude: nil, longitude: nil)

    @markers = @tools.map do |location|
        {
          lat: location.latitude,
          lng: location.longitude
          # infoWindow: { content: render_to_string(partial: "/tools/map_box", locals: { flat: flat }) }
        }
     end
  end

  def show
    @render_footer = true
    @tool = Tool.find(params[:id])
    @review = Review.new
    authorize @tool
    @markers = [@tool].map do |location|
        {
          lat: location.latitude,
          lng: location.longitude
          # infoWindow: { content: render_to_string(partial: "/tools/map_box", locals: { flat: flat }) }
        }
     end
    @tool = Tool.find(params[:id])
    @booking = Booking.new
    @user = current_user

  end

  def new
    @render_footer
    @tool = Tool.new
    authorize @tool
    @user = current_user
  end

  def create
    @render_footer
    @tool = Tool.new(tool_params)
    @tool.owner = current_user
    authorize @tool
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    authorize @tool
    @tool.destroy
    redirect_to tools_path
  end

  def edit
    @render_footer
    @tool = Tool.find(params[:id])
    authorize @tool
    @user = current_user
  end

  def update
    @render_footer = true
    @tool = Tool.find(params[:id])
    authorize @tool
    @tool.update(tool_params)
    redirect_to tool_path(@tool)
  end

  def mine
    @tools = current_user.my_tools
    authorize @tools
    @render_footer = true
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :description, :price, :category, :photo, :address, :term)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@tool, @booking], defaults: { input_html: { class: 'form-control form-inline' } } do |f| %>

 <%= f.text_field :start_date, class: "datepicker form-inline", placeholder: "Start date" %>
 <%= f.text_field :end_date, class: "datepicker form-inline", placeholder: "End date" %>
<br><br>
  <%= f.submit 'Book tool', class: 'btn btn-primary' %>
<% end %>




<%= content_for :js do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });
  <% end %>
<% end %>

app/views/bookings/create.html.erb
<h1>Booking Create</h1>
<!-- <h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>
 -->

app/views/bookings/destroy.html.erb
<h1>Bookings kaputt</h1>

app/views/bookings/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h2>Edit Booking <%= @booking.id %></h2>
      <div class="form-group">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
  <h1>All your bookings</h1>
  <% @bookings.each do |booking| %>
    <div class="col-xs-12 col-sm-12">
      <h2>link_to booking.tool.name, booking_path(booking)</h2>
        <%= link_to "Delete booking", booking_path(booking), method: :delete %>
    </div>
  <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h2>Make a New Booking </h2>
      <div class="form-group">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container text-center">
  <div class="big-box-t">
    <div class="box-left-t">
      <div class="inside-box-left">
        <%= image_tag @user.facebook_picture_url, width: 125 %>
        <h3><%= @user.first_name %></h3>
        <p><%= @user.email %></p>
        <p><%= @user.user_address %></p>
        <p><%= @user.payment_method %></p>
        <%= link_to 'My Tools', my_tools_path, class: "btn btn-primary" %>
      </div>
    </div>

    <div class="boxes-right-t">
      <div class="box-right-big-t">
        <h3>Booking successful!</h3>
        <%= cl_image_tag @booking.tool.photo, height: 250, crop: :fill %>
          <h3>Tool: <%= @booking.tool.name %></h3>
          <p>Owner: <%= @booking.tool.owner.email %></p>
           <p>Start date: <%= @booking.start_date %></p>
           <p>End date: <%= @booking.end_date %></p>
          <br><br>
          <%= link_to 'All tools', tools_path, class: 'btn btn-danger' %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/update.html.erb
<h1>Update a Booking</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>ToolUp</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <%= render 'shared/flashes' %>
  <%= render 'shared/navbar' %>
  <div id="min-page-height">
  <%= yield %>
  </div>
  <%= render 'shared/footer' if @render_footer %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag "map" %>
  <%= yield(:js) %>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="container text-center">
  <div class="big-box">
    <div class="box-left">
      <div class="inside-box-left">
        <%= image_tag @user.facebook_picture_url, width: 125 %>
        <h3><%= @user.first_name %></h3>
        <p><%= @user.email %></p>
        <p><%= @user.user_address %></p>
        <p><%= @user.payment_method %></p>
        <%= link_to 'My Tools', my_tools_path, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="boxes-right">
      <div class="box-right-up">
        <h3>Your bookings</h3>
          <% @bookings.each do |booking| %>
          <p><%= booking.tool.name %> -- Booked: <%= booking.created_at.strftime("%F") %>
            <%= link_to 'Delete', my_tools_path, class: "btn btn-primary" %>
          </p>
          <% end %>
      </div>
      <div class="box-right-down">
        <h3>Your reviews</h3>
        <% dashrev = Review.where(user_id: @user.id) %>
          <% dashrev.each do |dash| %>
          <p><%= dash.content %></p>
          <p> <%= link_to dash.tool.name, tool_path(dash.tool.id) %></p>
          <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/pages/homepage.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.4) 50%), url('https://image.ibb.co/iyfPwT/farmers_homepage.gif');">
  <div class="banner-content">
    <h1>ToolUp</h1>
    <p>Rent a tool from a local</p>
    <%= render 'shared/searchbar' %>
    </div>
  </div>
</div>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "shared/review_form", tool: @tool, review: @review %>');
<% else %>
  addReview('<%= j render "tools/review", review: @review %>');
  refreshForm('<%= j render "shared/review_form", tool: @tool, review: Review.new %>');
<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://cdn.wallpapersafari.com/46/75/gH1Pzq.png');">
  <div class="banner-content">
    <h1>ToolUp</h1>
    <p>Rent a tool from a local</p>
    <div class="searchbar">
   <!--    <a class="active" href="#home">Home</a> -->
      <input type="text" placeholder="Search...">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    ToolUp
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= "ToolUp"  %>
    <%=  image_tag "tulip.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Upload a tool", new_tool_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All tools", tools_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My tools", my_tools_path,  class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Upload a tool", new_tool_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "All tools", tools_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "My tools", my_tools_path,  class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<% tool = @tool
review = Review.new  %>
<%= simple_form_for [tool, review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_review_form.html.erb
<%= simple_form_for([tool, review], remote: true, defaults: { input_html: { class: 'form-control' } }) do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_searchbar.html.erb
<div class="searchbar">
  <%= form_tag tools_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-inline",
  placeholder: "Find a tool"%>
  <button type="submit"><i class="fa fa-search"></i></button>
<% end %>

app/views/tools/_card.html.erb
<div class="card-tool-container">
  <div class="card-tool">
    <div class="card-tool-image" style="background-image: url(<%= cl_image_path(tool.photo) %>)">
      <img class="card-tool-image-user" src=<%= tool.owner.facebook_picture_url %>>
    </div>
  <div class="card-text">
    <div class="card-category"><%= tool.category %></div>
      <div class="card-description">
        <h2 class="card-name"><%= link_to tool.name, tool_path(tool) %></h2>
        <p class="card-address"><%= tool.address %></p>
        <h3 class="review-count"><%= tool.reviews.count %> reviews</h3>
      </div>
    </div>
  </div>
</div>


<!-- <div class="row">
   <div class="col s12 m7">
     <div class="card">
       <div class="card-image">
         <img src="images/sample-1.jpg">
         <span class="card-title">Card Title</span>
       </div>
       <div class="card-content">
         <p>I am a very simple card. I am good at containing small bits of information.
         I am convenient because I require little markup to use effectively.</p>
       </div>
       <div class="card-action">
         <a href="#">This is a link</a>
       </div>
     </div>
   </div>
 </div> -->

app/views/tools/_form.html.erb
<%= simple_form_for @tool, defaults: { input_html: { class: 'form-control' } } do |f| %>

    <%= f.input :name, label: 'Name', placeholder: 'Big Tractor' %>
    <%= f.input :description, label: 'Description', placeholder: 'Does all the forming for us, yellow, too heavy to carry.' %>
    <%= f.input :price, label: 'Price', placeholder: 'price per day' %>
    <%= f.input :category, :collection => [['Hand Tools', :HANDTOOL], ['Power Tools', :POWERTOOL],['Machinery', :MACHINERY]], :checked => [:HANDTOOL], :include_hidden => false %>

    <%= f.input :photo, label: 'Upload pic' %>
    <%= f.input :address, label: 'Address', placeholder: 'addresss' %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit %>
<% end %>

app/views/tools/_review.html.erb
<div class="rewiew-wrapper" data-tool-id= '<%= @tool.id  %>' >
  <p><%= review.content%></p>
  <p>by <%= review.user.first_name %></p>
</div>

app/views/tools/destroy.js.erb
document.querySelector("[data-tool-id='<%= @tool.id %>']")
  .remove();

app/views/tools/edit.html.erb
<div class="container text-center">
  <div class="big-box-t">
    <div class="box-left-t">
      <div class="inside-box-left">
        <%= image_tag @user.facebook_picture_url, width: 125 %>
        <h3><%= @user.first_name %></h3>
        <p><%= @user.email %></p>
        <p><%= @user.user_address %></p>
        <p><%= @user.payment_method %></p>
        <%= link_to 'My Tools', my_tools_path, class: "btn btn-primary" %>
      </div>
    </div>

    <div class="boxes-right-t">
      <div class="box-right-big-t">
        <h3>Edit a new tool</h3>
        <div class="form-group">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/index.html.erb
  <div class = "container-fluid">
    <div class="col-sm-8">
      <%= render 'shared/searchbar' %>
    </div>
      <div class="row">
        <% @tools.each do |tool| %>
        <div class="col-xs-6 col-md-4">
          <%= render 'card', tool: tool %>
        </div>
        <% end %>
      </div>
    </div>
      <div id="map" data-markers="<%= @markers.to_json %>"></div>
  </div>

app/views/tools/mine.html.erb
<div class="my-container">
  <div class="row">
  <% @tools.each do |tool| %>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <%= render 'card', tool: tool %>
    </div>
  <% end %>
  </div>
</div>

app/views/tools/new.html.erb
<div class="container text-center">
  <div class="big-box-t">
    <div class="box-left-t">
      <div class="inside-box-left">
        <%= image_tag @user.facebook_picture_url, width: 125 %>
        <h3><%= @user.first_name %></h3>
        <p><%= @user.email %></p>
        <p><%= @user.user_address %></p>
        <p><%= @user.payment_method %></p>
        <%= link_to 'My Tools', my_tools_path, class: "btn btn-primary" %>
      </div>
    </div>

    <div class="boxes-right-t">
      <div class="box-right-big-t">
        <h3>Upload a new tool</h3>
        <div class="form-group">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/show.html.erb
<!-- Sexy Bootstrap Thumbmnail -->
<div class="container text-center">
  <div class="big-box-t">
    <div class="box-left-t">
      <div class="inside-box-left">
          <%= image_tag @user.facebook_picture_url, width: 125 %>
          <h3><%= @user.first_name %></h3>
          <p><%= @user.email %></p>
          <p><%= @user.user_address %></p>
          <p><%= @user.payment_method %></p>
          <%= link_to 'My Tools', my_tools_path, class: "btn btn-primary" %>
          <p><br>
             <%= link_to 'All tools', tools_path, class: 'btn btn-danger' %>
          </p>
      </div>
    </div>

    <div class="boxes-right-t">
      <div class="box-right-big-t">
         <%= cl_image_tag @tool.photo, height: 150, crop: :fill %>
          <h3><%= @tool.name %></h3>
          <p>About: <%= @tool.description %></p>
          <p>Price: <%= @tool.price %></p>

          <% if @tool.owner == current_user %>
            <%= link_to 'Edit', edit_tool_path, class: 'btn btn-success' %></p>
          <% else %>
           <div class="form-group">
              <%= render 'bookings/form' %>
            </div>
          <% end %>
          <br><br>
          <%= link_to 'More tools', tools_path, class: 'btn btn-danger' %>

          <h2>Tool's reviews</h2>
          <ul class="list-unstyled" id="reviews">
            <% @tool.reviews.each do |review| %>
              <%= render 'tools/review', review: review %>
            <% end %>
          </ul>

          <div class = "description-tools">
            <% if current_user.bookings.where(tool_id: @tool.id).first %>
            <%= render 'shared/review_form', tool: @tool, review: @review %>
            <% end %>

          </div>
      </div>
    </div>
  </div>
</div>